---
  - name: Update the inventory for the Ansible Deployment
    hosts: localhost
    connection: local
    gather_facts: no

    tasks:

    - name: Get an AAP API Token and store it as new_token
      register: new_token
      ansible.builtin.uri:
        url: "https://{{ controller_url }}/api/v2/tokens/"
        method: POST
        user: "{{ controller_user }}"
        password: "{{ controller_passwd }}"
        validate_certs: no
        force_basic_auth: yes
        status_code: 201
        return_content: yes       
    
    - name: Update the AAP AWS Managed Inventory with the controllers
      loop: "{{ my_controller_server_data['instances'] }}"
      awx.awx.host:
        controller_host: "https://{{ controller_url }}"
        controller_username: "{{ controller_user }}"
        controller_oauthtoken: "{{ new_token.json.token }}"
        name: "{{ item['public_dns_name'] }}"
        inventory: "AAP AWS Inventory - Managed"
        state: present
        enabled: true
        validate_certs: false

    - name: Create a group for our Automation Controllers
      loop: "{{ my_controller_server_data['instances'] }}"
      awx.awx.group:
        controller_host: "https://{{ controller_url }}"
        controller_username: "{{ controller_user }}"
        controller_oauthtoken: "{{ new_token.json.token }}"
        name: control
        description: "Automation Controller Group"
        inventory: "AAP AWS Inventory - Managed"
        hosts: "{{ item['public_dns_name'] }}"
        preserve_existing_hosts: true